// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: api/proto/infer.proto

package inferpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferAPI_Infer_FullMethodName = "/inferAPI.InferAPI/Infer"
)

// InferAPIClient is the client API for InferAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InferAPIClient interface {
	Infer(ctx context.Context, in *InferRequest, opts ...grpc.CallOption) (*InferResponse, error)
}

type inferAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewInferAPIClient(cc grpc.ClientConnInterface) InferAPIClient {
	return &inferAPIClient{cc}
}

func (c *inferAPIClient) Infer(ctx context.Context, in *InferRequest, opts ...grpc.CallOption) (*InferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InferResponse)
	err := c.cc.Invoke(ctx, InferAPI_Infer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferAPIServer is the server API for InferAPI service.
// All implementations must embed UnimplementedInferAPIServer
// for forward compatibility.
type InferAPIServer interface {
	Infer(context.Context, *InferRequest) (*InferResponse, error)
	mustEmbedUnimplementedInferAPIServer()
}

// UnimplementedInferAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferAPIServer struct{}

func (UnimplementedInferAPIServer) Infer(context.Context, *InferRequest) (*InferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Infer not implemented")
}
func (UnimplementedInferAPIServer) mustEmbedUnimplementedInferAPIServer() {}
func (UnimplementedInferAPIServer) testEmbeddedByValue()                  {}

// UnsafeInferAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferAPIServer will
// result in compilation errors.
type UnsafeInferAPIServer interface {
	mustEmbedUnimplementedInferAPIServer()
}

func RegisterInferAPIServer(s grpc.ServiceRegistrar, srv InferAPIServer) {
	// If the following call panics, it indicates UnimplementedInferAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferAPI_ServiceDesc, srv)
}

func _InferAPI_Infer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferAPIServer).Infer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferAPI_Infer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferAPIServer).Infer(ctx, req.(*InferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InferAPI_ServiceDesc is the grpc.ServiceDesc for InferAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inferAPI.InferAPI",
	HandlerType: (*InferAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Infer",
			Handler:    _InferAPI_Infer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/infer.proto",
}
