// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/infer.proto

package inferpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InferRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ModelId        string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	InputData      []float32              `protobuf:"fixed32,2,rep,packed,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`
	ScalingEnabled bool                   `protobuf:"varint,3,opt,name=scaling_enabled,json=scalingEnabled,proto3" json:"scaling_enabled,omitempty"`
	IsForwarded    bool                   `protobuf:"varint,4,opt,name=is_forwarded,json=isForwarded,proto3" json:"is_forwarded,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InferRequest) Reset() {
	*x = InferRequest{}
	mi := &file_api_proto_infer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferRequest) ProtoMessage() {}

func (x *InferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_infer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferRequest.ProtoReflect.Descriptor instead.
func (*InferRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_infer_proto_rawDescGZIP(), []int{0}
}

func (x *InferRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *InferRequest) GetInputData() []float32 {
	if x != nil {
		return x.InputData
	}
	return nil
}

func (x *InferRequest) GetScalingEnabled() bool {
	if x != nil {
		return x.ScalingEnabled
	}
	return false
}

func (x *InferRequest) GetIsForwarded() bool {
	if x != nil {
		return x.IsForwarded
	}
	return false
}

type InferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Prediction    float32                `protobuf:"fixed32,2,opt,name=prediction,proto3" json:"prediction,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferResponse) Reset() {
	*x = InferResponse{}
	mi := &file_api_proto_infer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferResponse) ProtoMessage() {}

func (x *InferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_infer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferResponse.ProtoReflect.Descriptor instead.
func (*InferResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_infer_proto_rawDescGZIP(), []int{1}
}

func (x *InferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InferResponse) GetPrediction() float32 {
	if x != nil {
		return x.Prediction
	}
	return 0
}

func (x *InferResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_api_proto_infer_proto protoreflect.FileDescriptor

const file_api_proto_infer_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/infer.proto\x12\binferAPI\"\x94\x01\n" +
	"\fInferRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"input_data\x18\x02 \x03(\x02R\tinputData\x12'\n" +
	"\x0fscaling_enabled\x18\x03 \x01(\bR\x0escalingEnabled\x12!\n" +
	"\fis_forwarded\x18\x04 \x01(\bR\visForwarded\"n\n" +
	"\rInferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1e\n" +
	"\n" +
	"prediction\x18\x02 \x01(\x02R\n" +
	"prediction\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2D\n" +
	"\bInferAPI\x128\n" +
	"\x05Infer\x12\x16.inferAPI.InferRequest\x1a\x17.inferAPI.InferResponseB\"Z internal/common/pb/infer;inferpbb\x06proto3"

var (
	file_api_proto_infer_proto_rawDescOnce sync.Once
	file_api_proto_infer_proto_rawDescData []byte
)

func file_api_proto_infer_proto_rawDescGZIP() []byte {
	file_api_proto_infer_proto_rawDescOnce.Do(func() {
		file_api_proto_infer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_infer_proto_rawDesc), len(file_api_proto_infer_proto_rawDesc)))
	})
	return file_api_proto_infer_proto_rawDescData
}

var file_api_proto_infer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_infer_proto_goTypes = []any{
	(*InferRequest)(nil),  // 0: inferAPI.InferRequest
	(*InferResponse)(nil), // 1: inferAPI.InferResponse
}
var file_api_proto_infer_proto_depIdxs = []int32{
	0, // 0: inferAPI.InferAPI.Infer:input_type -> inferAPI.InferRequest
	1, // 1: inferAPI.InferAPI.Infer:output_type -> inferAPI.InferResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_infer_proto_init() }
func file_api_proto_infer_proto_init() {
	if File_api_proto_infer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_infer_proto_rawDesc), len(file_api_proto_infer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_infer_proto_goTypes,
		DependencyIndexes: file_api_proto_infer_proto_depIdxs,
		MessageInfos:      file_api_proto_infer_proto_msgTypes,
	}.Build()
	File_api_proto_infer_proto = out.File
	file_api_proto_infer_proto_goTypes = nil
	file_api_proto_infer_proto_depIdxs = nil
}
