// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/node.proto

package nodepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type None struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *None) Reset() {
	*x = None{}
	mi := &file_api_proto_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *None) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*None) ProtoMessage() {}

func (x *None) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use None.ProtoReflect.Descriptor instead.
func (*None) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{0}
}

type MemoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Free          int64                  `protobuf:"varint,2,opt,name=free,proto3" json:"free,omitempty"`
	Used          int64                  `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryInfo) Reset() {
	*x = MemoryInfo{}
	mi := &file_api_proto_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryInfo) ProtoMessage() {}

func (x *MemoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryInfo.ProtoReflect.Descriptor instead.
func (*MemoryInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{1}
}

func (x *MemoryInfo) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MemoryInfo) GetFree() int64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *MemoryInfo) GetUsed() int64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *MemoryInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type StorageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Free          int64                  `protobuf:"varint,2,opt,name=free,proto3" json:"free,omitempty"`
	Used          int64                  `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
	ReadSpeed     int64                  `protobuf:"varint,4,opt,name=read_speed,json=readSpeed,proto3" json:"read_speed,omitempty"`
	WriteSpeed    int64                  `protobuf:"varint,5,opt,name=write_speed,json=writeSpeed,proto3" json:"write_speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageInfo) Reset() {
	*x = StorageInfo{}
	mi := &file_api_proto_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageInfo) ProtoMessage() {}

func (x *StorageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageInfo.ProtoReflect.Descriptor instead.
func (*StorageInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{2}
}

func (x *StorageInfo) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *StorageInfo) GetFree() int64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *StorageInfo) GetUsed() int64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *StorageInfo) GetReadSpeed() int64 {
	if x != nil {
		return x.ReadSpeed
	}
	return 0
}

func (x *StorageInfo) GetWriteSpeed() int64 {
	if x != nil {
		return x.WriteSpeed
	}
	return 0
}

type ComputeDevice struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Vendor         string                 `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Model          string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Memory         int64                  `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	ComputeUnits   int64                  `protobuf:"varint,5,opt,name=compute_units,json=computeUnits,proto3" json:"compute_units,omitempty"`
	Tops           float32                `protobuf:"fixed32,6,opt,name=tops,proto3" json:"tops,omitempty"`
	PowerDrawWatts int64                  `protobuf:"varint,7,opt,name=power_draw_watts,json=powerDrawWatts,proto3" json:"power_draw_watts,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ComputeDevice) Reset() {
	*x = ComputeDevice{}
	mi := &file_api_proto_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeDevice) ProtoMessage() {}

func (x *ComputeDevice) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeDevice.ProtoReflect.Descriptor instead.
func (*ComputeDevice) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{3}
}

func (x *ComputeDevice) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ComputeDevice) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *ComputeDevice) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ComputeDevice) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *ComputeDevice) GetComputeUnits() int64 {
	if x != nil {
		return x.ComputeUnits
	}
	return 0
}

func (x *ComputeDevice) GetTops() float32 {
	if x != nil {
		return x.Tops
	}
	return 0
}

func (x *ComputeDevice) GetPowerDrawWatts() int64 {
	if x != nil {
		return x.PowerDrawWatts
	}
	return 0
}

type ResourceCapabilities struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Memory         *MemoryInfo            `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage        *StorageInfo           `protobuf:"bytes,2,opt,name=storage,proto3" json:"storage,omitempty"`
	ComputeDevices []*ComputeDevice       `protobuf:"bytes,3,rep,name=compute_devices,json=computeDevices,proto3" json:"compute_devices,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResourceCapabilities) Reset() {
	*x = ResourceCapabilities{}
	mi := &file_api_proto_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceCapabilities) ProtoMessage() {}

func (x *ResourceCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceCapabilities.ProtoReflect.Descriptor instead.
func (*ResourceCapabilities) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceCapabilities) GetMemory() *MemoryInfo {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *ResourceCapabilities) GetStorage() *StorageInfo {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *ResourceCapabilities) GetComputeDevices() []*ComputeDevice {
	if x != nil {
		return x.ComputeDevices
	}
	return nil
}

type NodeMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OsType        string                 `protobuf:"bytes,1,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMetadata) Reset() {
	*x = NodeMetadata{}
	mi := &file_api_proto_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetadata) ProtoMessage() {}

func (x *NodeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetadata.ProtoReflect.Descriptor instead.
func (*NodeMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{5}
}

func (x *NodeMetadata) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *NodeMetadata) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *NodeMetadata) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type NodeInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NodeId               string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ip                   string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Metadata             *NodeMetadata          `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ResourceCapabilities *ResourceCapabilities  `protobuf:"bytes,6,opt,name=resource_capabilities,json=resourceCapabilities,proto3" json:"resource_capabilities,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_api_proto_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{6}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NodeInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NodeInfo) GetMetadata() *NodeMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *NodeInfo) GetResourceCapabilities() *ResourceCapabilities {
	if x != nil {
		return x.ResourceCapabilities
	}
	return nil
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_api_proto_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type UpdateNodeRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NodeId               string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Metadata             *NodeMetadata          `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ResourceCapabilities *ResourceCapabilities  `protobuf:"bytes,3,opt,name=resource_capabilities,json=resourceCapabilities,proto3" json:"resource_capabilities,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateNodeRequest) Reset() {
	*x = UpdateNodeRequest{}
	mi := &file_api_proto_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeRequest) ProtoMessage() {}

func (x *UpdateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UpdateNodeRequest) GetMetadata() *NodeMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateNodeRequest) GetResourceCapabilities() *ResourceCapabilities {
	if x != nil {
		return x.ResourceCapabilities
	}
	return nil
}

type BoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolResponse) Reset() {
	*x = BoolResponse{}
	mi := &file_api_proto_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolResponse) ProtoMessage() {}

func (x *BoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolResponse.ProtoReflect.Descriptor instead.
func (*BoolResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{9}
}

func (x *BoolResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type NodeID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeID) Reset() {
	*x = NodeID{}
	mi := &file_api_proto_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeID) ProtoMessage() {}

func (x *NodeID) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeID.ProtoReflect.Descriptor instead.
func (*NodeID) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{10}
}

func (x *NodeID) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_api_proto_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{11}
}

func (x *ListNodesResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_api_proto_node_proto protoreflect.FileDescriptor

const file_api_proto_node_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/node.proto\x12\x0fnodeRegistryAPI\"\x06\n" +
	"\x04None\"^\n" +
	"\n" +
	"MemoryInfo\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x12\n" +
	"\x04free\x18\x02 \x01(\x03R\x04free\x12\x12\n" +
	"\x04used\x18\x03 \x01(\x03R\x04used\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"\x8b\x01\n" +
	"\vStorageInfo\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x12\n" +
	"\x04free\x18\x02 \x01(\x03R\x04free\x12\x12\n" +
	"\x04used\x18\x03 \x01(\x03R\x04used\x12\x1d\n" +
	"\n" +
	"read_speed\x18\x04 \x01(\x03R\treadSpeed\x12\x1f\n" +
	"\vwrite_speed\x18\x05 \x01(\x03R\n" +
	"writeSpeed\"\xcc\x01\n" +
	"\rComputeDevice\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x16\n" +
	"\x06memory\x18\x04 \x01(\x03R\x06memory\x12#\n" +
	"\rcompute_units\x18\x05 \x01(\x03R\fcomputeUnits\x12\x12\n" +
	"\x04tops\x18\x06 \x01(\x02R\x04tops\x12(\n" +
	"\x10power_draw_watts\x18\a \x01(\x03R\x0epowerDrawWatts\"\xcc\x01\n" +
	"\x14ResourceCapabilities\x123\n" +
	"\x06memory\x18\x01 \x01(\v2\x1b.nodeRegistryAPI.MemoryInfoR\x06memory\x126\n" +
	"\astorage\x18\x02 \x01(\v2\x1c.nodeRegistryAPI.StorageInfoR\astorage\x12G\n" +
	"\x0fcompute_devices\x18\x03 \x03(\v2\x1e.nodeRegistryAPI.ComputeDeviceR\x0ecomputeDevices\"h\n" +
	"\fNodeMetadata\x12\x17\n" +
	"\aos_type\x18\x01 \x01(\tR\x06osType\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\"\xf2\x01\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x129\n" +
	"\bmetadata\x18\x05 \x01(\v2\x1d.nodeRegistryAPI.NodeMetadataR\bmetadata\x12Z\n" +
	"\x15resource_capabilities\x18\x06 \x01(\v2%.nodeRegistryAPI.ResourceCapabilitiesR\x14resourceCapabilities\"/\n" +
	"\x14RegisterNodeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xc3\x01\n" +
	"\x11UpdateNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x129\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1d.nodeRegistryAPI.NodeMetadataR\bmetadata\x12Z\n" +
	"\x15resource_capabilities\x18\x03 \x01(\v2%.nodeRegistryAPI.ResourceCapabilitiesR\x14resourceCapabilities\"(\n" +
	"\fBoolResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"!\n" +
	"\x06NodeID\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"D\n" +
	"\x11ListNodesResponse\x12/\n" +
	"\x05nodes\x18\x01 \x03(\v2\x19.nodeRegistryAPI.NodeInfoR\x05nodes2\x85\x03\n" +
	"\x0fNodeRegistryAPI\x12P\n" +
	"\fRegisterNode\x12\x19.nodeRegistryAPI.NodeInfo\x1a%.nodeRegistryAPI.RegisterNodeResponse\x12H\n" +
	"\x0eDeRegisterNode\x12\x17.nodeRegistryAPI.NodeID\x1a\x1d.nodeRegistryAPI.BoolResponse\x12O\n" +
	"\n" +
	"UpdateNode\x12\".nodeRegistryAPI.UpdateNodeRequest\x1a\x1d.nodeRegistryAPI.BoolResponse\x12=\n" +
	"\aGetNode\x12\x17.nodeRegistryAPI.NodeID\x1a\x19.nodeRegistryAPI.NodeInfo\x12F\n" +
	"\tListNodes\x12\x15.nodeRegistryAPI.None\x1a\".nodeRegistryAPI.ListNodesResponseB Z\x1einternal/common/pb/node;nodepbb\x06proto3"

var (
	file_api_proto_node_proto_rawDescOnce sync.Once
	file_api_proto_node_proto_rawDescData []byte
)

func file_api_proto_node_proto_rawDescGZIP() []byte {
	file_api_proto_node_proto_rawDescOnce.Do(func() {
		file_api_proto_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_node_proto_rawDesc), len(file_api_proto_node_proto_rawDesc)))
	})
	return file_api_proto_node_proto_rawDescData
}

var file_api_proto_node_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_node_proto_goTypes = []any{
	(*None)(nil),                 // 0: nodeRegistryAPI.None
	(*MemoryInfo)(nil),           // 1: nodeRegistryAPI.MemoryInfo
	(*StorageInfo)(nil),          // 2: nodeRegistryAPI.StorageInfo
	(*ComputeDevice)(nil),        // 3: nodeRegistryAPI.ComputeDevice
	(*ResourceCapabilities)(nil), // 4: nodeRegistryAPI.ResourceCapabilities
	(*NodeMetadata)(nil),         // 5: nodeRegistryAPI.NodeMetadata
	(*NodeInfo)(nil),             // 6: nodeRegistryAPI.NodeInfo
	(*RegisterNodeResponse)(nil), // 7: nodeRegistryAPI.RegisterNodeResponse
	(*UpdateNodeRequest)(nil),    // 8: nodeRegistryAPI.UpdateNodeRequest
	(*BoolResponse)(nil),         // 9: nodeRegistryAPI.BoolResponse
	(*NodeID)(nil),               // 10: nodeRegistryAPI.NodeID
	(*ListNodesResponse)(nil),    // 11: nodeRegistryAPI.ListNodesResponse
}
var file_api_proto_node_proto_depIdxs = []int32{
	1,  // 0: nodeRegistryAPI.ResourceCapabilities.memory:type_name -> nodeRegistryAPI.MemoryInfo
	2,  // 1: nodeRegistryAPI.ResourceCapabilities.storage:type_name -> nodeRegistryAPI.StorageInfo
	3,  // 2: nodeRegistryAPI.ResourceCapabilities.compute_devices:type_name -> nodeRegistryAPI.ComputeDevice
	5,  // 3: nodeRegistryAPI.NodeInfo.metadata:type_name -> nodeRegistryAPI.NodeMetadata
	4,  // 4: nodeRegistryAPI.NodeInfo.resource_capabilities:type_name -> nodeRegistryAPI.ResourceCapabilities
	5,  // 5: nodeRegistryAPI.UpdateNodeRequest.metadata:type_name -> nodeRegistryAPI.NodeMetadata
	4,  // 6: nodeRegistryAPI.UpdateNodeRequest.resource_capabilities:type_name -> nodeRegistryAPI.ResourceCapabilities
	6,  // 7: nodeRegistryAPI.ListNodesResponse.nodes:type_name -> nodeRegistryAPI.NodeInfo
	6,  // 8: nodeRegistryAPI.NodeRegistryAPI.RegisterNode:input_type -> nodeRegistryAPI.NodeInfo
	10, // 9: nodeRegistryAPI.NodeRegistryAPI.DeRegisterNode:input_type -> nodeRegistryAPI.NodeID
	8,  // 10: nodeRegistryAPI.NodeRegistryAPI.UpdateNode:input_type -> nodeRegistryAPI.UpdateNodeRequest
	10, // 11: nodeRegistryAPI.NodeRegistryAPI.GetNode:input_type -> nodeRegistryAPI.NodeID
	0,  // 12: nodeRegistryAPI.NodeRegistryAPI.ListNodes:input_type -> nodeRegistryAPI.None
	7,  // 13: nodeRegistryAPI.NodeRegistryAPI.RegisterNode:output_type -> nodeRegistryAPI.RegisterNodeResponse
	9,  // 14: nodeRegistryAPI.NodeRegistryAPI.DeRegisterNode:output_type -> nodeRegistryAPI.BoolResponse
	9,  // 15: nodeRegistryAPI.NodeRegistryAPI.UpdateNode:output_type -> nodeRegistryAPI.BoolResponse
	6,  // 16: nodeRegistryAPI.NodeRegistryAPI.GetNode:output_type -> nodeRegistryAPI.NodeInfo
	11, // 17: nodeRegistryAPI.NodeRegistryAPI.ListNodes:output_type -> nodeRegistryAPI.ListNodesResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_node_proto_init() }
func file_api_proto_node_proto_init() {
	if File_api_proto_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_node_proto_rawDesc), len(file_api_proto_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_node_proto_goTypes,
		DependencyIndexes: file_api_proto_node_proto_depIdxs,
		MessageInfos:      file_api_proto_node_proto_msgTypes,
	}.Build()
	File_api_proto_node_proto = out.File
	file_api_proto_node_proto_goTypes = nil
	file_api_proto_node_proto_depIdxs = nil
}
