// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: api/proto/node.proto

package nodepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeRegistryAPI_RegisterNode_FullMethodName   = "/nodeRegistryAPI.NodeRegistryAPI/RegisterNode"
	NodeRegistryAPI_DeRegisterNode_FullMethodName = "/nodeRegistryAPI.NodeRegistryAPI/DeRegisterNode"
	NodeRegistryAPI_UpdateNode_FullMethodName     = "/nodeRegistryAPI.NodeRegistryAPI/UpdateNode"
	NodeRegistryAPI_GetNode_FullMethodName        = "/nodeRegistryAPI.NodeRegistryAPI/GetNode"
	NodeRegistryAPI_ListNodes_FullMethodName      = "/nodeRegistryAPI.NodeRegistryAPI/ListNodes"
)

// NodeRegistryAPIClient is the client API for NodeRegistryAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeRegistryAPIClient interface {
	RegisterNode(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	DeRegisterNode(ctx context.Context, in *NodeID, opts ...grpc.CallOption) (*BoolResponse, error)
	UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	GetNode(ctx context.Context, in *NodeID, opts ...grpc.CallOption) (*NodeInfo, error)
	ListNodes(ctx context.Context, in *None, opts ...grpc.CallOption) (*ListNodesResponse, error)
}

type nodeRegistryAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeRegistryAPIClient(cc grpc.ClientConnInterface) NodeRegistryAPIClient {
	return &nodeRegistryAPIClient{cc}
}

func (c *nodeRegistryAPIClient) RegisterNode(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, NodeRegistryAPI_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRegistryAPIClient) DeRegisterNode(ctx context.Context, in *NodeID, opts ...grpc.CallOption) (*BoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, NodeRegistryAPI_DeRegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRegistryAPIClient) UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, NodeRegistryAPI_UpdateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRegistryAPIClient) GetNode(ctx context.Context, in *NodeID, opts ...grpc.CallOption) (*NodeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeInfo)
	err := c.cc.Invoke(ctx, NodeRegistryAPI_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRegistryAPIClient) ListNodes(ctx context.Context, in *None, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, NodeRegistryAPI_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeRegistryAPIServer is the server API for NodeRegistryAPI service.
// All implementations must embed UnimplementedNodeRegistryAPIServer
// for forward compatibility.
type NodeRegistryAPIServer interface {
	RegisterNode(context.Context, *NodeInfo) (*RegisterNodeResponse, error)
	DeRegisterNode(context.Context, *NodeID) (*BoolResponse, error)
	UpdateNode(context.Context, *UpdateNodeRequest) (*BoolResponse, error)
	GetNode(context.Context, *NodeID) (*NodeInfo, error)
	ListNodes(context.Context, *None) (*ListNodesResponse, error)
	mustEmbedUnimplementedNodeRegistryAPIServer()
}

// UnimplementedNodeRegistryAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeRegistryAPIServer struct{}

func (UnimplementedNodeRegistryAPIServer) RegisterNode(context.Context, *NodeInfo) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedNodeRegistryAPIServer) DeRegisterNode(context.Context, *NodeID) (*BoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeRegisterNode not implemented")
}
func (UnimplementedNodeRegistryAPIServer) UpdateNode(context.Context, *UpdateNodeRequest) (*BoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNode not implemented")
}
func (UnimplementedNodeRegistryAPIServer) GetNode(context.Context, *NodeID) (*NodeInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedNodeRegistryAPIServer) ListNodes(context.Context, *None) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedNodeRegistryAPIServer) mustEmbedUnimplementedNodeRegistryAPIServer() {}
func (UnimplementedNodeRegistryAPIServer) testEmbeddedByValue()                         {}

// UnsafeNodeRegistryAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeRegistryAPIServer will
// result in compilation errors.
type UnsafeNodeRegistryAPIServer interface {
	mustEmbedUnimplementedNodeRegistryAPIServer()
}

func RegisterNodeRegistryAPIServer(s grpc.ServiceRegistrar, srv NodeRegistryAPIServer) {
	// If the following call panics, it indicates UnimplementedNodeRegistryAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeRegistryAPI_ServiceDesc, srv)
}

func _NodeRegistryAPI_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRegistryAPIServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeRegistryAPI_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRegistryAPIServer).RegisterNode(ctx, req.(*NodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRegistryAPI_DeRegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRegistryAPIServer).DeRegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeRegistryAPI_DeRegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRegistryAPIServer).DeRegisterNode(ctx, req.(*NodeID))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRegistryAPI_UpdateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRegistryAPIServer).UpdateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeRegistryAPI_UpdateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRegistryAPIServer).UpdateNode(ctx, req.(*UpdateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRegistryAPI_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRegistryAPIServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeRegistryAPI_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRegistryAPIServer).GetNode(ctx, req.(*NodeID))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRegistryAPI_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(None)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRegistryAPIServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeRegistryAPI_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRegistryAPIServer).ListNodes(ctx, req.(*None))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeRegistryAPI_ServiceDesc is the grpc.ServiceDesc for NodeRegistryAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeRegistryAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodeRegistryAPI.NodeRegistryAPI",
	HandlerType: (*NodeRegistryAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _NodeRegistryAPI_RegisterNode_Handler,
		},
		{
			MethodName: "DeRegisterNode",
			Handler:    _NodeRegistryAPI_DeRegisterNode_Handler,
		},
		{
			MethodName: "UpdateNode",
			Handler:    _NodeRegistryAPI_UpdateNode_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _NodeRegistryAPI_GetNode_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _NodeRegistryAPI_ListNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/node.proto",
}
