// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/heartbeat.proto

package heartbeatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeID        string                 `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestHeartbeatRequest) Reset() {
	*x = RequestHeartbeatRequest{}
	mi := &file_api_proto_heartbeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHeartbeatRequest) ProtoMessage() {}

func (x *RequestHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_heartbeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*RequestHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *RequestHeartbeatRequest) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

type ModelReplicaDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicaId     string                 `protobuf:"bytes,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	FilePath      string                 `protobuf:"bytes,5,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	ModelType     string                 `protobuf:"bytes,6,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	ModelSize     int64                  `protobuf:"varint,7,opt,name=model_size,json=modelSize,proto3" json:"model_size,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,9,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelReplicaDetails) Reset() {
	*x = ModelReplicaDetails{}
	mi := &file_api_proto_heartbeat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelReplicaDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelReplicaDetails) ProtoMessage() {}

func (x *ModelReplicaDetails) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_heartbeat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelReplicaDetails.ProtoReflect.Descriptor instead.
func (*ModelReplicaDetails) Descriptor() ([]byte, []int) {
	return file_api_proto_heartbeat_proto_rawDescGZIP(), []int{1}
}

func (x *ModelReplicaDetails) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *ModelReplicaDetails) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelReplicaDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelReplicaDetails) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModelReplicaDetails) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ModelReplicaDetails) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelReplicaDetails) GetModelSize() int64 {
	if x != nil {
		return x.ModelSize
	}
	return 0
}

func (x *ModelReplicaDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ModelReplicaDetails) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ModelReplicaDetails) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RequestHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeID        string                 `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	ModelReplicas []*ModelReplicaDetails `protobuf:"bytes,2,rep,name=ModelReplicas,proto3" json:"ModelReplicas,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestHeartbeatResponse) Reset() {
	*x = RequestHeartbeatResponse{}
	mi := &file_api_proto_heartbeat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHeartbeatResponse) ProtoMessage() {}

func (x *RequestHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_heartbeat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*RequestHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_heartbeat_proto_rawDescGZIP(), []int{2}
}

func (x *RequestHeartbeatResponse) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *RequestHeartbeatResponse) GetModelReplicas() []*ModelReplicaDetails {
	if x != nil {
		return x.ModelReplicas
	}
	return nil
}

func (x *RequestHeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_heartbeat_proto protoreflect.FileDescriptor

const file_api_proto_heartbeat_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/heartbeat.proto\x12\fheartbeatAPI\"1\n" +
	"\x17RequestHeartbeatRequest\x12\x16\n" +
	"\x06nodeID\x18\x01 \x01(\tR\x06nodeID\"\xb4\x02\n" +
	"\x13ModelReplicaDetails\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\tR\treplicaId\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1b\n" +
	"\tfile_path\x18\x05 \x01(\tR\bfilePath\x12\x1d\n" +
	"\n" +
	"model_type\x18\x06 \x01(\tR\tmodelType\x12\x1d\n" +
	"\n" +
	"model_size\x18\a \x01(\x03R\tmodelSize\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\t \x01(\x05R\terrorCode\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\"\x95\x01\n" +
	"\x18RequestHeartbeatResponse\x12\x16\n" +
	"\x06nodeID\x18\x01 \x01(\tR\x06nodeID\x12G\n" +
	"\rModelReplicas\x18\x02 \x03(\v2!.heartbeatAPI.ModelReplicaDetailsR\rModelReplicas\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess2q\n" +
	"\fHeartbeatAPI\x12a\n" +
	"\x10RequestHeartbeat\x12%.heartbeatAPI.RequestHeartbeatRequest\x1a&.heartbeatAPI.RequestHeartbeatResponseB*Z(internal/common/pb/heartbeat;heartbeatpbb\x06proto3"

var (
	file_api_proto_heartbeat_proto_rawDescOnce sync.Once
	file_api_proto_heartbeat_proto_rawDescData []byte
)

func file_api_proto_heartbeat_proto_rawDescGZIP() []byte {
	file_api_proto_heartbeat_proto_rawDescOnce.Do(func() {
		file_api_proto_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_heartbeat_proto_rawDesc), len(file_api_proto_heartbeat_proto_rawDesc)))
	})
	return file_api_proto_heartbeat_proto_rawDescData
}

var file_api_proto_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_heartbeat_proto_goTypes = []any{
	(*RequestHeartbeatRequest)(nil),  // 0: heartbeatAPI.RequestHeartbeatRequest
	(*ModelReplicaDetails)(nil),      // 1: heartbeatAPI.ModelReplicaDetails
	(*RequestHeartbeatResponse)(nil), // 2: heartbeatAPI.RequestHeartbeatResponse
}
var file_api_proto_heartbeat_proto_depIdxs = []int32{
	1, // 0: heartbeatAPI.RequestHeartbeatResponse.ModelReplicas:type_name -> heartbeatAPI.ModelReplicaDetails
	0, // 1: heartbeatAPI.HeartbeatAPI.RequestHeartbeat:input_type -> heartbeatAPI.RequestHeartbeatRequest
	2, // 2: heartbeatAPI.HeartbeatAPI.RequestHeartbeat:output_type -> heartbeatAPI.RequestHeartbeatResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_heartbeat_proto_init() }
func file_api_proto_heartbeat_proto_init() {
	if File_api_proto_heartbeat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_heartbeat_proto_rawDesc), len(file_api_proto_heartbeat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_heartbeat_proto_goTypes,
		DependencyIndexes: file_api_proto_heartbeat_proto_depIdxs,
		MessageInfos:      file_api_proto_heartbeat_proto_msgTypes,
	}.Build()
	File_api_proto_heartbeat_proto = out.File
	file_api_proto_heartbeat_proto_goTypes = nil
	file_api_proto_heartbeat_proto_depIdxs = nil
}
