// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: api/proto/heartbeat.proto

package heartbeatpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HeartbeatAPI_RequestHeartbeat_FullMethodName = "/heartbeatAPI.HeartbeatAPI/RequestHeartbeat"
)

// HeartbeatAPIClient is the client API for HeartbeatAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HeartbeatAPIClient interface {
	RequestHeartbeat(ctx context.Context, in *RequestHeartbeatRequest, opts ...grpc.CallOption) (*RequestHeartbeatResponse, error)
}

type heartbeatAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewHeartbeatAPIClient(cc grpc.ClientConnInterface) HeartbeatAPIClient {
	return &heartbeatAPIClient{cc}
}

func (c *heartbeatAPIClient) RequestHeartbeat(ctx context.Context, in *RequestHeartbeatRequest, opts ...grpc.CallOption) (*RequestHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestHeartbeatResponse)
	err := c.cc.Invoke(ctx, HeartbeatAPI_RequestHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HeartbeatAPIServer is the server API for HeartbeatAPI service.
// All implementations must embed UnimplementedHeartbeatAPIServer
// for forward compatibility.
type HeartbeatAPIServer interface {
	RequestHeartbeat(context.Context, *RequestHeartbeatRequest) (*RequestHeartbeatResponse, error)
	mustEmbedUnimplementedHeartbeatAPIServer()
}

// UnimplementedHeartbeatAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHeartbeatAPIServer struct{}

func (UnimplementedHeartbeatAPIServer) RequestHeartbeat(context.Context, *RequestHeartbeatRequest) (*RequestHeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestHeartbeat not implemented")
}
func (UnimplementedHeartbeatAPIServer) mustEmbedUnimplementedHeartbeatAPIServer() {}
func (UnimplementedHeartbeatAPIServer) testEmbeddedByValue()                      {}

// UnsafeHeartbeatAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HeartbeatAPIServer will
// result in compilation errors.
type UnsafeHeartbeatAPIServer interface {
	mustEmbedUnimplementedHeartbeatAPIServer()
}

func RegisterHeartbeatAPIServer(s grpc.ServiceRegistrar, srv HeartbeatAPIServer) {
	// If the following call panics, it indicates UnimplementedHeartbeatAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HeartbeatAPI_ServiceDesc, srv)
}

func _HeartbeatAPI_RequestHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeartbeatAPIServer).RequestHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HeartbeatAPI_RequestHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeartbeatAPIServer).RequestHeartbeat(ctx, req.(*RequestHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HeartbeatAPI_ServiceDesc is the grpc.ServiceDesc for HeartbeatAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HeartbeatAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "heartbeatAPI.HeartbeatAPI",
	HandlerType: (*HeartbeatAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestHeartbeat",
			Handler:    _HeartbeatAPI_RequestHeartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/heartbeat.proto",
}
