// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: api/proto/deploy.proto

package deploypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeployAPI_DeployModel_FullMethodName = "/deployAPI.DeployAPI/DeployModel"
)

// DeployAPIClient is the client API for DeployAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeployAPIClient interface {
	DeployModel(ctx context.Context, in *DeployModelRequest, opts ...grpc.CallOption) (*DeployModelResponse, error)
}

type deployAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewDeployAPIClient(cc grpc.ClientConnInterface) DeployAPIClient {
	return &deployAPIClient{cc}
}

func (c *deployAPIClient) DeployModel(ctx context.Context, in *DeployModelRequest, opts ...grpc.CallOption) (*DeployModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployModelResponse)
	err := c.cc.Invoke(ctx, DeployAPI_DeployModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeployAPIServer is the server API for DeployAPI service.
// All implementations must embed UnimplementedDeployAPIServer
// for forward compatibility.
type DeployAPIServer interface {
	DeployModel(context.Context, *DeployModelRequest) (*DeployModelResponse, error)
	mustEmbedUnimplementedDeployAPIServer()
}

// UnimplementedDeployAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeployAPIServer struct{}

func (UnimplementedDeployAPIServer) DeployModel(context.Context, *DeployModelRequest) (*DeployModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeployModel not implemented")
}
func (UnimplementedDeployAPIServer) mustEmbedUnimplementedDeployAPIServer() {}
func (UnimplementedDeployAPIServer) testEmbeddedByValue()                   {}

// UnsafeDeployAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeployAPIServer will
// result in compilation errors.
type UnsafeDeployAPIServer interface {
	mustEmbedUnimplementedDeployAPIServer()
}

func RegisterDeployAPIServer(s grpc.ServiceRegistrar, srv DeployAPIServer) {
	// If the following call panics, it indicates UnimplementedDeployAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeployAPI_ServiceDesc, srv)
}

func _DeployAPI_DeployModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployAPIServer).DeployModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployAPI_DeployModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployAPIServer).DeployModel(ctx, req.(*DeployModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeployAPI_ServiceDesc is the grpc.ServiceDesc for DeployAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeployAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deployAPI.DeployAPI",
	HandlerType: (*DeployAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeployModel",
			Handler:    _DeployAPI_DeployModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/deploy.proto",
}

const (
	ModelTransferService_DownloadModel_FullMethodName = "/deployAPI.ModelTransferService/DownloadModel"
	ModelTransferService_UploadModel_FullMethodName   = "/deployAPI.ModelTransferService/UploadModel"
)

// ModelTransferServiceClient is the client API for ModelTransferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModelTransferServiceClient interface {
	// DownloadModel streams a model file from the control plane to the caller.
	DownloadModel(ctx context.Context, in *ModelDownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ModelChunk], error)
	// UploadModel streams a model file from the caller to the control plane.
	// The first chunk must carry ModelUploadMetadata; subsequent chunks carry raw bytes.
	UploadModel(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ModelUploadChunk, ModelUploadResponse], error)
}

type modelTransferServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModelTransferServiceClient(cc grpc.ClientConnInterface) ModelTransferServiceClient {
	return &modelTransferServiceClient{cc}
}

func (c *modelTransferServiceClient) DownloadModel(ctx context.Context, in *ModelDownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ModelChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ModelTransferService_ServiceDesc.Streams[0], ModelTransferService_DownloadModel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ModelDownloadRequest, ModelChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModelTransferService_DownloadModelClient = grpc.ServerStreamingClient[ModelChunk]

func (c *modelTransferServiceClient) UploadModel(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ModelUploadChunk, ModelUploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ModelTransferService_ServiceDesc.Streams[1], ModelTransferService_UploadModel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ModelUploadChunk, ModelUploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModelTransferService_UploadModelClient = grpc.ClientStreamingClient[ModelUploadChunk, ModelUploadResponse]

// ModelTransferServiceServer is the server API for ModelTransferService service.
// All implementations must embed UnimplementedModelTransferServiceServer
// for forward compatibility.
type ModelTransferServiceServer interface {
	// DownloadModel streams a model file from the control plane to the caller.
	DownloadModel(*ModelDownloadRequest, grpc.ServerStreamingServer[ModelChunk]) error
	// UploadModel streams a model file from the caller to the control plane.
	// The first chunk must carry ModelUploadMetadata; subsequent chunks carry raw bytes.
	UploadModel(grpc.ClientStreamingServer[ModelUploadChunk, ModelUploadResponse]) error
	mustEmbedUnimplementedModelTransferServiceServer()
}

// UnimplementedModelTransferServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelTransferServiceServer struct{}

func (UnimplementedModelTransferServiceServer) DownloadModel(*ModelDownloadRequest, grpc.ServerStreamingServer[ModelChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadModel not implemented")
}
func (UnimplementedModelTransferServiceServer) UploadModel(grpc.ClientStreamingServer[ModelUploadChunk, ModelUploadResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadModel not implemented")
}
func (UnimplementedModelTransferServiceServer) mustEmbedUnimplementedModelTransferServiceServer() {}
func (UnimplementedModelTransferServiceServer) testEmbeddedByValue()                              {}

// UnsafeModelTransferServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelTransferServiceServer will
// result in compilation errors.
type UnsafeModelTransferServiceServer interface {
	mustEmbedUnimplementedModelTransferServiceServer()
}

func RegisterModelTransferServiceServer(s grpc.ServiceRegistrar, srv ModelTransferServiceServer) {
	// If the following call panics, it indicates UnimplementedModelTransferServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelTransferService_ServiceDesc, srv)
}

func _ModelTransferService_DownloadModel_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ModelDownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ModelTransferServiceServer).DownloadModel(m, &grpc.GenericServerStream[ModelDownloadRequest, ModelChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModelTransferService_DownloadModelServer = grpc.ServerStreamingServer[ModelChunk]

func _ModelTransferService_UploadModel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ModelTransferServiceServer).UploadModel(&grpc.GenericServerStream[ModelUploadChunk, ModelUploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModelTransferService_UploadModelServer = grpc.ClientStreamingServer[ModelUploadChunk, ModelUploadResponse]

// ModelTransferService_ServiceDesc is the grpc.ServiceDesc for ModelTransferService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelTransferService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deployAPI.ModelTransferService",
	HandlerType: (*ModelTransferServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadModel",
			Handler:       _ModelTransferService_DownloadModel_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadModel",
			Handler:       _ModelTransferService_UploadModel_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/deploy.proto",
}
