// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: api/proto/model.proto

package modelpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelRegistryAPI_RegisterModel_FullMethodName   = "/modelRegistryAPI.ModelRegistryAPI/RegisterModel"
	ModelRegistryAPI_DeRegisterModel_FullMethodName = "/modelRegistryAPI.ModelRegistryAPI/DeRegisterModel"
	ModelRegistryAPI_UpdateModel_FullMethodName     = "/modelRegistryAPI.ModelRegistryAPI/UpdateModel"
	ModelRegistryAPI_GetModel_FullMethodName        = "/modelRegistryAPI.ModelRegistryAPI/GetModel"
	ModelRegistryAPI_ListModels_FullMethodName      = "/modelRegistryAPI.ModelRegistryAPI/ListModels"
)

// ModelRegistryAPIClient is the client API for ModelRegistryAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModelRegistryAPIClient interface {
	RegisterModel(ctx context.Context, in *ModelInfo, opts ...grpc.CallOption) (*BoolResponse, error)
	DeRegisterModel(ctx context.Context, in *ModelID, opts ...grpc.CallOption) (*BoolResponse, error)
	UpdateModel(ctx context.Context, in *UpdateModelRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	GetModel(ctx context.Context, in *ModelID, opts ...grpc.CallOption) (*ModelInfo, error)
	ListModels(ctx context.Context, in *None, opts ...grpc.CallOption) (*ListModelsResponse, error)
}

type modelRegistryAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewModelRegistryAPIClient(cc grpc.ClientConnInterface) ModelRegistryAPIClient {
	return &modelRegistryAPIClient{cc}
}

func (c *modelRegistryAPIClient) RegisterModel(ctx context.Context, in *ModelInfo, opts ...grpc.CallOption) (*BoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, ModelRegistryAPI_RegisterModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelRegistryAPIClient) DeRegisterModel(ctx context.Context, in *ModelID, opts ...grpc.CallOption) (*BoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, ModelRegistryAPI_DeRegisterModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelRegistryAPIClient) UpdateModel(ctx context.Context, in *UpdateModelRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, ModelRegistryAPI_UpdateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelRegistryAPIClient) GetModel(ctx context.Context, in *ModelID, opts ...grpc.CallOption) (*ModelInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelInfo)
	err := c.cc.Invoke(ctx, ModelRegistryAPI_GetModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelRegistryAPIClient) ListModels(ctx context.Context, in *None, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, ModelRegistryAPI_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelRegistryAPIServer is the server API for ModelRegistryAPI service.
// All implementations must embed UnimplementedModelRegistryAPIServer
// for forward compatibility.
type ModelRegistryAPIServer interface {
	RegisterModel(context.Context, *ModelInfo) (*BoolResponse, error)
	DeRegisterModel(context.Context, *ModelID) (*BoolResponse, error)
	UpdateModel(context.Context, *UpdateModelRequest) (*BoolResponse, error)
	GetModel(context.Context, *ModelID) (*ModelInfo, error)
	ListModels(context.Context, *None) (*ListModelsResponse, error)
	mustEmbedUnimplementedModelRegistryAPIServer()
}

// UnimplementedModelRegistryAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelRegistryAPIServer struct{}

func (UnimplementedModelRegistryAPIServer) RegisterModel(context.Context, *ModelInfo) (*BoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterModel not implemented")
}
func (UnimplementedModelRegistryAPIServer) DeRegisterModel(context.Context, *ModelID) (*BoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeRegisterModel not implemented")
}
func (UnimplementedModelRegistryAPIServer) UpdateModel(context.Context, *UpdateModelRequest) (*BoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateModel not implemented")
}
func (UnimplementedModelRegistryAPIServer) GetModel(context.Context, *ModelID) (*ModelInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModel not implemented")
}
func (UnimplementedModelRegistryAPIServer) ListModels(context.Context, *None) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedModelRegistryAPIServer) mustEmbedUnimplementedModelRegistryAPIServer() {}
func (UnimplementedModelRegistryAPIServer) testEmbeddedByValue()                          {}

// UnsafeModelRegistryAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelRegistryAPIServer will
// result in compilation errors.
type UnsafeModelRegistryAPIServer interface {
	mustEmbedUnimplementedModelRegistryAPIServer()
}

func RegisterModelRegistryAPIServer(s grpc.ServiceRegistrar, srv ModelRegistryAPIServer) {
	// If the following call panics, it indicates UnimplementedModelRegistryAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelRegistryAPI_ServiceDesc, srv)
}

func _ModelRegistryAPI_RegisterModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelRegistryAPIServer).RegisterModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelRegistryAPI_RegisterModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelRegistryAPIServer).RegisterModel(ctx, req.(*ModelInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelRegistryAPI_DeRegisterModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelRegistryAPIServer).DeRegisterModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelRegistryAPI_DeRegisterModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelRegistryAPIServer).DeRegisterModel(ctx, req.(*ModelID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelRegistryAPI_UpdateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelRegistryAPIServer).UpdateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelRegistryAPI_UpdateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelRegistryAPIServer).UpdateModel(ctx, req.(*UpdateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelRegistryAPI_GetModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelRegistryAPIServer).GetModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelRegistryAPI_GetModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelRegistryAPIServer).GetModel(ctx, req.(*ModelID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelRegistryAPI_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(None)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelRegistryAPIServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelRegistryAPI_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelRegistryAPIServer).ListModels(ctx, req.(*None))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelRegistryAPI_ServiceDesc is the grpc.ServiceDesc for ModelRegistryAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelRegistryAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "modelRegistryAPI.ModelRegistryAPI",
	HandlerType: (*ModelRegistryAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterModel",
			Handler:    _ModelRegistryAPI_RegisterModel_Handler,
		},
		{
			MethodName: "DeRegisterModel",
			Handler:    _ModelRegistryAPI_DeRegisterModel_Handler,
		},
		{
			MethodName: "UpdateModel",
			Handler:    _ModelRegistryAPI_UpdateModel_Handler,
		},
		{
			MethodName: "GetModel",
			Handler:    _ModelRegistryAPI_GetModel_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _ModelRegistryAPI_ListModels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/model.proto",
}
