// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/discovery.proto

package discoverypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesRequest) Reset() {
	*x = GetNodesRequest{}
	mi := &file_api_proto_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesRequest) ProtoMessage() {}

func (x *GetNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesRequest.ProtoReflect.Descriptor instead.
func (*GetNodesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_discovery_proto_rawDescGZIP(), []int{0}
}

type NodeEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeEndpoint) Reset() {
	*x = NodeEndpoint{}
	mi := &file_api_proto_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEndpoint) ProtoMessage() {}

func (x *NodeEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEndpoint.ProtoReflect.Descriptor instead.
func (*NodeEndpoint) Descriptor() ([]byte, []int) {
	return file_api_proto_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *NodeEndpoint) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeEndpoint) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NodeEndpoint) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type GetNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeEndpoint        `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesResponse) Reset() {
	*x = GetNodesResponse{}
	mi := &file_api_proto_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesResponse) ProtoMessage() {}

func (x *GetNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesResponse.ProtoReflect.Descriptor instead.
func (*GetNodesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *GetNodesResponse) GetNodes() []*NodeEndpoint {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_api_proto_discovery_proto protoreflect.FileDescriptor

const file_api_proto_discovery_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/discovery.proto\x12\fdiscoveryAPI\"\x11\n" +
	"\x0fGetNodesRequest\"K\n" +
	"\fNodeEndpoint\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"D\n" +
	"\x10GetNodesResponse\x120\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1a.discoveryAPI.NodeEndpointR\x05nodes2Y\n" +
	"\fDiscoveryAPI\x12I\n" +
	"\bGetNodes\x12\x1d.discoveryAPI.GetNodesRequest\x1a\x1e.discoveryAPI.GetNodesResponseB*Z(internal/common/pb/discovery;discoverypbb\x06proto3"

var (
	file_api_proto_discovery_proto_rawDescOnce sync.Once
	file_api_proto_discovery_proto_rawDescData []byte
)

func file_api_proto_discovery_proto_rawDescGZIP() []byte {
	file_api_proto_discovery_proto_rawDescOnce.Do(func() {
		file_api_proto_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_discovery_proto_rawDesc), len(file_api_proto_discovery_proto_rawDesc)))
	})
	return file_api_proto_discovery_proto_rawDescData
}

var file_api_proto_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_discovery_proto_goTypes = []any{
	(*GetNodesRequest)(nil),  // 0: discoveryAPI.GetNodesRequest
	(*NodeEndpoint)(nil),     // 1: discoveryAPI.NodeEndpoint
	(*GetNodesResponse)(nil), // 2: discoveryAPI.GetNodesResponse
}
var file_api_proto_discovery_proto_depIdxs = []int32{
	1, // 0: discoveryAPI.GetNodesResponse.nodes:type_name -> discoveryAPI.NodeEndpoint
	0, // 1: discoveryAPI.DiscoveryAPI.GetNodes:input_type -> discoveryAPI.GetNodesRequest
	2, // 2: discoveryAPI.DiscoveryAPI.GetNodes:output_type -> discoveryAPI.GetNodesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_discovery_proto_init() }
func file_api_proto_discovery_proto_init() {
	if File_api_proto_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_discovery_proto_rawDesc), len(file_api_proto_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_discovery_proto_goTypes,
		DependencyIndexes: file_api_proto_discovery_proto_depIdxs,
		MessageInfos:      file_api_proto_discovery_proto_msgTypes,
	}.Build()
	File_api_proto_discovery_proto = out.File
	file_api_proto_discovery_proto_goTypes = nil
	file_api_proto_discovery_proto_depIdxs = nil
}
