// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: api/proto/discovery.proto

package discoverypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiscoveryAPI_GetNodes_FullMethodName = "/discoveryAPI.DiscoveryAPI/GetNodes"
)

// DiscoveryAPIClient is the client API for DiscoveryAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscoveryAPIClient interface {
	GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error)
}

type discoveryAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoveryAPIClient(cc grpc.ClientConnInterface) DiscoveryAPIClient {
	return &discoveryAPIClient{cc}
}

func (c *discoveryAPIClient) GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodesResponse)
	err := c.cc.Invoke(ctx, DiscoveryAPI_GetNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscoveryAPIServer is the server API for DiscoveryAPI service.
// All implementations must embed UnimplementedDiscoveryAPIServer
// for forward compatibility.
type DiscoveryAPIServer interface {
	GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error)
	mustEmbedUnimplementedDiscoveryAPIServer()
}

// UnimplementedDiscoveryAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiscoveryAPIServer struct{}

func (UnimplementedDiscoveryAPIServer) GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodes not implemented")
}
func (UnimplementedDiscoveryAPIServer) mustEmbedUnimplementedDiscoveryAPIServer() {}
func (UnimplementedDiscoveryAPIServer) testEmbeddedByValue()                      {}

// UnsafeDiscoveryAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscoveryAPIServer will
// result in compilation errors.
type UnsafeDiscoveryAPIServer interface {
	mustEmbedUnimplementedDiscoveryAPIServer()
}

func RegisterDiscoveryAPIServer(s grpc.ServiceRegistrar, srv DiscoveryAPIServer) {
	// If the following call panics, it indicates UnimplementedDiscoveryAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiscoveryAPI_ServiceDesc, srv)
}

func _DiscoveryAPI_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryAPIServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryAPI_GetNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryAPIServer).GetNodes(ctx, req.(*GetNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiscoveryAPI_ServiceDesc is the grpc.ServiceDesc for DiscoveryAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscoveryAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discoveryAPI.DiscoveryAPI",
	HandlerType: (*DiscoveryAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodes",
			Handler:    _DiscoveryAPI_GetNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/discovery.proto",
}
